# https://www.blackvoid.club/grafana-8-influxdb-2-telegraf-2021-monitoring-stack/
version: '3.9'

services:
  grafana:
    image: grafana/grafana:8.5.3
    container_name: grafana
    depends_on:
      - influxdb
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana-volume:/var/lib/grafana
    user: '472'
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-volume/data:/var/lib/influxdb
      - ./influxdb-volume/config:/etc/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER=$INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD=$INFLUXDB_USER_PASSWORD
      - INFLUXDB_DB=$INFLUXDB_DB
    restart: always
  
  tempmanager:
    image: tempmanager:latest
    container_name: tempmanager
    depends_on:
      - influxdb
    volumes:
      - ./tempmanager:/home/user/tempmanager:ro
      - /sys/bus/w1/devices:/sys/bus/w1/devices:ro
    environment:
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER=$INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD=$INFLUXDB_USER_PASSWORD
      - INFLUXDB_DB=$INFLUXDB_DB
      - INFLUXDB_URL=$INFLUXDB_URL
      - TEMP_SENSOR_ID=$TEMP_SENSOR_ID
    tty: true # to keep container open with tail -f /dev/null
    #entrypoint: python ./tempmanager/read_temp-sensor.py
